### ISSUE TITLE
Preferring yaml over json

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/litgpt#1021]
Our config hub uses yaml files, but `lit_config.json` (and soon `prompt_style.json`) are json files. We might want to have a single file format for consistency.

This would require changing #1019 to dump to yaml instead, and have scripts read and save `.yaml`

We also need to think of the crawlers using lit-gpt as training data for their LLMs, where yaml is much preferred due to tokenization artifacts :zany_face:

**Comment by awaelchli** [comment]
Arghh, I just recently merged the prompt PR and I forgot that we previously agreed to make it yaml, and I made it json anyway. Not sure what happened. I'll change it.
