### ISSUE TITLE
Dataset Size after Preprocessing in Pretrainning Tiny Llama

### ISSUE THREAD

**Issue by yuanyaaa** [Lightning-AI/litgpt#1023]
When pre training the dataset, we need to download the SlimPajama and Startcode datasets separately and preprocess them. However, we found that the processed data sizes are 2.4T(the size of train is 2.4T, test is 2.1G and validation is 2.1G ) and 1010G (based on 1024), respectively which is different with the size you provided(https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/pretrain_tinyllama.md#:~:text=You%20will%20require%201.1%20TB%20of%20disk%20space%20for%20Starcoder%20and%202.5%20TB%20of%20space%20for%20the%20SlimPajama%20dataset.). 

The scripts we ran are exactly the same as yours. What do you think might be the problem.
<img width="998" alt="image" src="https://github.com/Lightning-AI/lit-gpt/assets/49089811/aec742d8-2e7b-4a03-ab11-f0595acf88f1">

**Comment by awaelchli** [comment]
Hey @yuanyaaa 

After preprocessing the data, we deleted the raw files. So I can't give you the exact size we measured in bytes. 
But I'm pretty sure the information in the link

> You will require 1.1 TB of disk space for Starcoder and 2.5 TB of space for the SlimPajama dataset.

is just us rounding up to the next integer after the decimal point. It's just to give the user an approximate number they should keep in mind when downloading the data.

**Comment by awaelchli** [comment]
This is the studio we used for TinyLlama. It also includes the data
https://lightning.ai/lightning-ai/studios/pretrain-llms-tinyllama-1-1b

under `/teamspace/s3_connections/tinyllama-template/` if you want to double-check things with the data.

**Comment by yuanyaaa** [comment]
Thank you so much!!! I will use it to double-check

**Comment by yuanyaaa** [comment]
Thank you so much!!! I will use it to double-check
