### ISSUE TITLE
Enable positional arguments for some CLI commands

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1028]
There are a few CLI commands where the first argument is so commonly used and unambiguous that it would make sense to allow passing as positional. A few examples I can think of:

```
python download.py org/name
vs
python download.py --repo_id=org/name
```

```
python merge_lora.py path/to/checkpoint
vs
python merge_lora.py --checkpoint_dir path/to/checkpoint
```

```
python chat.py path/to/checkpoint
vs
python chat.py --checkpoint_dir path/to/checkpoint
```
Currently, the CLI enforces us to name all arguments.

**Alternatively**
Maybe no action is needed at the moment, and we can enable this through the top level cli wrapper `litgpt x y`.

cc @carmocca for brains

**Comment by carmocca** [comment]
In the past, consistency was preferred: https://github.com/Lightning-AI/lit-gpt/pull/462#issuecomment-1718078712. I would agree with being consistent especially for common arguments like `--checkpoint_dir`

It can also be confusing because jsonargparse forces you to always pass it positionally or always by keyword. Knowing which one to use in which script can be annoying.

Also, in general, relying on position if there are multiple positional arguments can become a problem.

**Comment by awaelchli** [comment]
> It can also be confusing because jsonargparse forces you to always pass it positionally or always by keyword. Knowing which one to use in which script can be annoying.

If it is true then I agree it would be bad to do this switch. But I just tested this by marking the signature with `, *,` and it works well:

```py
from jsonargparse import CLI


def main(positional: int, *, optional: bool = False):
    print(f"positional={positional}, optional={optional}")


if __name__ == "__main__":
    CLI(main)
```

```
❯ python mycli.py 
usage: mycli.py [-h] [--config CONFIG] [--print_config[=flags]] [--optional {true,false}] positional
error: Validation failed: Key "positional" is required but not included in config object or its value is None.

❯ python mycli.py 1
positional=1, optional=False

❯python mycli.py 1 True
usage: mycli.py [-h] [--config CONFIG] [--print_config[=flags]] [--optional {true,false}] positional
error: Unrecognized arguments: True


❯ python mycli.py 1 --optional True
positional=1, optional=True

```

Would we be ok with adding `,*` in scripts where we have one main argument and rarely used optional arguments?

**Comment by carmocca** [comment]
What I meant is that you cannot do this:

```python
python mycli.py --positional 123
usage: kk.py [-h] [--config CONFIG] [--print_config[=flags]] [--optional {true,false}] positional
error: Unrecognized arguments: --positional
```

**Comment by awaelchli** [comment]
Oh, that's a mildly annoying limitation :(

**Comment by rasbt** [comment]
On the other hand, even if the current way means more typing, I think the current way is a bit more clear
