### ISSUE TITLE
Enable tab completion

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1032]
Jsonargparse supports tab completion:
https://jsonargparse.readthedocs.io/en/v4.27.5/index.html#tab-completion

We could try to enable this on our new CLI. I gave it a quick try but couldn't make it work yet.

**Comment by Andrei-Aksionov** [comment]
Every time I typed commands, I wanted this feature to exist.

**Comment by rasbt** [comment]
This would be amazing!

**Comment by carmocca** [comment]
I was never able to get this to work. It's also not clear how to integrate it into the entrypoints CLI. Can we call `register-python-argcomplete` automatically for the user?

**Comment by awaelchli** [comment]
I tried last week and couldn't get it to work, neither on MacOS nor on Linux. I tried both registering a CLI script explicitly and also installing the global hook to no avail.

**Comment by carmocca** [comment]
Lets close this until theres proof we can make it work
