### ISSUE TITLE
bugs convert lit model

### ISSUE THREAD

**Issue by batman-do** [Lightning-AI/litgpt#1058]
![image](https://github.com/Lightning-AI/litgpt/assets/77484083/dee2d338-1706-478d-b0ef-6195979038c9)

how to fix that ? @carmocca

**Comment by rasbt** [comment]
Thanks for reporting and sorry about the hassle! We had some changes and improvements in the model conversion process in the last couple of weeks. Let us know if this issue still persist and we can reinvestigate.
