### ISSUE TITLE
Installation of extras

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1064]
Since LitGPT will be made into a package, we will need to have a way to install extras. Otherwise it is cumbersome to install a bunch of packages manually.

At least:
```
pip install litgpt[all]
```

Could also go more granular, like

```
pip install litgpt[pretrain]
```
But I don't know what makes sense there.

@carmocca

**Comment by carmocca** [comment]
I'm adding "[all]" in #1068. No need to be more granular at the moment.

It will also require that the package is installed to be used.
