### ISSUE TITLE
Add references to example studios

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1070]
We have several studios that use litgpt. #1069 removes a notebook, and a Colab link. These should probably be links to Studios anyways. We have several finetuning Studios for example.

**Comment by rasbt** [comment]
I had a section "External Projects using LitGPT" in mind for the new Readme. We can add the Studios, but also projects like TinyLlama and the NeurIPS competition

**Comment by rasbt** [comment]
This should be all added in the new README :)
