### ISSUE TITLE
Guard against calling modules as a script

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1088]
If someone makes a typo and runs 

```
# 1
python litgpt/lora.py --checkpoint_dir ...
```

instead of

```
#2
python litgpt/finetune/lora.py --checkpoint_dir ...
```

Then nothing happens (no output, nothing), which could be confusing because the names of the files are very similar, and I can imagine this is something that could easily happen to someone when using tab-autocomplete perhaps. 

I wonder, should we raise an error in case someone tries to execute the core module files? I think we could probably do that with a friendly message in an `if __name__ == """__main__"""` section.

**Comment by rasbt** [comment]
Actually, I think this could easily happen, because we have 

```
python litgpt/pretrain.py
```

but 

```
python litgpt/finetune/lora.py
```

**Comment by carmocca** [comment]
When #996 is done, the tutorials will use the CLI so this won't be a problem
