### ISSUE TITLE
Convert custom TinyLlama (custom config) to Pytorch or HuggingFace format

### ISSUE THREAD

**Issue by eljanmahammadli** [Lightning-AI/litgpt#1095]
Hello everyone,

Firstly, thanks for everyone who has contributed to this amazing repo. It is life saving.
My problem is that, I have pretrained custom TinyLlama with different configs (`n_layer`, `n_head`, `n_embd`.) on my custom dataset. I have seen ways to convert the .pth checkpoint to Pytorch module or HuggingFace transformers. But how to do that for my custom model which has different layers and params from the original version.

Any help or guidance is appreciated as it is important for me. As you know pretraining is difficult and takes time.

**Comment by eljanmahammadli** [comment]
I have changed following hyperparameters when pretraining.

- n_layer=6

- n_head=4

- n_embd=128

**Comment by eljanmahammadli** [comment]
@carmocca could you please take a look at that?

**Comment by Andrei-Aksionov** [comment]
Hey @eljanmahammadli 
As @carmocca pointed out, you can specify all the changed parameters in HF config (or provide them as kwargs during loading).
That means that after you converted a model, as specified in the [tutorial](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/convert_lit_models.md#a-finetuning-and-conversion-tutorial), you need to load it, but, compared to the tutorial, your code should be something like:
```python
import torch
from transformers import AutoModel

state_dict = torch.load('out/hf-tinyllama/converted_model.pth')
model = AutoModel.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T",
    num_hidden_layers=6,
    num_attention_heads=4,
    hidden_size=128,
    state_dict=state_dict,
)
```

**Comment by eljanmahammadli** [comment]
@carmocca @Andrei-Aksionov 
Thanks a lot, I was able to use both ways. I didn’t know we are able to initialize model like this.
