### ISSUE TITLE
Remove verbose output in `litgpt chat`

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1120]
`litpgt chat` prints the entire model config at the beginning. Maybe now we could drop these prints or hide them under `--verbose`. 

Printing the model name at the start should be sufficient, if even needed:

```
Now chatting with Llama 2 7B.
To exit, press 'Enter' on an empty prompt.

>> Prompt:
```

**Comment by rasbt** [comment]
Yes, this would be nice
