### ISSUE TITLE
Finetune tutorials broken link in main branch

### ISSUE THREAD

**Issue by carafelix** [Lightning-AI/litgpt#1158]
In [finetune.md tutorial](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/finetune.md#finetuning-how-to-guides) there is a broken link at `Finetuning how-to guides.`  [Full-parameter finetuning](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/funetuning.md) is giving 404 reference error.

**Comment by rasbt** [comment]
Thanks for the note, fixing it now!
