### ISSUE TITLE
Add `litgpt eval` CLI

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1168]
Add CLI support for model evaluation, e.g., `litgpt eval ...`

**Comment by carmocca** [comment]
I didn't do this because I wasn't sure if we prefer to recommend converting to HF and using their lm_eval integration since it's more developed and avoids possible differences in the evaluation logic

**Comment by rasbt** [comment]
Makes sense. I think we maybe want to revisit this some time, either updating the `lm_eval` adapter or maybe adding a utility function that does the conversion to HF and calls the original harness. I.e., combining all these steps

```
litgpt convert from_litgpt \
    --checkpoint_dir checkpoints/microsoft/phi-2 \
    --output_dir out/converted_model/

cp checkpoints/microsoft/phi-2/config.json out/converted_model/config.json

cp checkpoints/microsoft/phi-2/tokenizer*
out/converted_model
```

```
import torch
from transformers import AutoModel

# Load model
state_dict = torch.load('out/converted_model/model.pth')
model = AutoModel.from_pretrained(
    "microsoft/phi-2", state_dict=state_dict
)

# Save .safetensors files
model.save_pretrained("out/converted_model/")
```

```
lm_eval --model hf \
    --model_args pretrained="out/converted_model" \
    --tasks "hellaswag,gsm8k,truthfulqa_mc2,mmlu,winogrande,arc_challenge" \
    --device "cuda:0" \
    --batch_size 4
```

Into one:

```bash
litgpt eval --checkpoint_dir ... \
  --lm_eval.tasks ... \
  --lm_eval.device \
  --lm_eval.batch_size ...

```

What do you think?

**Comment by carmocca** [comment]
I think combining those steps is the quickest way to improve this. Upgrading to latest lm_eval and reaching feature parity seems like a big task at the moment

**Comment by rasbt** [comment]
Sounds good! Let me add this to my list. I can probably put something together today. We can always revisit this later, but this would indeed be the easier v1 to get this working.
