### ISSUE TITLE
Mistral 7B v0.2

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1183]
We have Mistral 7B v 0.1, and this is probably an easy one to add: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/tree/main

The 7B 0.2 Base model was just shared at the Mistral hackathon today and should probably be in the Hub soon too.

**Comment by carmocca** [comment]
We already have Instruct v0.2 in: https://github.com/Lightning-AI/litgpt/blob/main/litgpt/config.py#L1393

When the pretrained model is added, if the config is exactly the same you can use the `model_name` argument https://github.com/Lightning-AI/litgpt/blob/main/tutorials/download_model_weights.md#finetunes-and-other-model-variants

**Comment by rasbt** [comment]
Ah yes, I somehow overlooked this. I really need to wear glasses haha. Let's stay tuned for when the model gets added to the hub. Just checked [here](https://huggingface.co/mistralai) and it doesn't seem to have landed yet.

**Comment by rasbt** [comment]
There seems to be a GGUF version at [https://huggingface.co/bartowski/Mistral-7B-v0.2-hf-GGUF](https://huggingface.co/bartowski/Mistral-7B-v0.2-hf-GGUF), but I suggest we wait for the official one under [https://huggingface.co/mistralai/](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/tree/main)

**Comment by Andrei-Aksionov** [comment]
People at MistralAI are so badass, that they provide a [direct link](https://lnkd.in/gs-DhTjj) to download the weights.

**Comment by rasbt** [comment]
Haha thanks!

The only caveat is it doesn't come with any prior usage or license information and you don't know what you are downloading. I think we should probably wait for the Hub version.

**Comment by Andrei-Aksionov** [comment]
> and you don't know what you are downloading.

I would say that this is the biggest issue.
Given the size of the archive it can contain anything, starting from a collection of memes to some interesting, relatively short, videos.

<img src="https://github.com/Lightning-AI/litgpt/assets/58434077/dd4dbb64-9e8a-4f84-bca8-ae0d99e46b27" width="300" height="200" />

----

So, let's definitely weight.
