### ISSUE TITLE
Data prep in pretraining tutorial does not work

### ISSUE THREAD

**Issue by RuABraun** [Lightning-AI/litgpt#1196]
The data preparation commands [here](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/pretrain_tinyllama.md#prepare-the-datasets-for-training) do not work for me. I get an error
```  
File "/var/spool/slurmd/job143071/slurm_script", line 27, in prepare_item
    for row in f:
zstd.ZstdError: zstd decompress error: Unknown frame descriptor
```

If I try and open a file manually it also fails.

```
>>> import zstandard as zstd
>>> dctx = zstd.ZstdDecompressor()
>>> with open('data/slimpajama-raw/validation/chunk1/example_holdout_0.jsonl.zst', 'rb') as fh:
...     dctx = zstd.ZstdDecompressor()
...     reader = dctx.stream_reader(fh)
...     while True:
...             chunk = reader.read(65536)
...             if not chunk:
...                     break
... 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
zstd.ZstdError: zstd decompress error: Unknown frame descriptor
```

The starcoder data preparation also fails with `pyarrow.lib.ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`

Could the data have been prepared with much older versions? My zstandard is `0.22.0`

**Comment by carmocca** [comment]
cc @awaelchli

Have you checked that the files were properly downloaded? Do they look right if you manually inspect them?

It would also be useful if you could share the complete error stacktrace

**Comment by awaelchli** [comment]
I checked in my wandb logs, the version of zstandard was 0.22. The zstd files are just compressed json files, so there is nothing special there. So if they can't be decompressed, they are definitely corrupt. That the starcoder also fails also hints that there is an issue with the files. How big is the dataset after download (before running prepare)? It should be roughly 893 + 290 GB total.

**Comment by RuABraun** [comment]
My bad, looks like I messed something up in the download the files don't look right. Appreciate the quick response! Closing for now
