### ISSUE TITLE
Is there any plan to add Megatron-LM support to enable lit-gpt to train extreme size model?

### ISSUE THREAD

**Issue by TeddLi** [Lightning-AI/litgpt#1215]
There are very few opensource repo supporting extreme size model (e.g., 70B, 175B) training. Just wondering if there is any time frame for lit-gpt supporting that

**Comment by rasbt** [comment]
Good question. 70B models are already (70B Llama 2, 180B Falcon, 70B CodeLlama). 

You can find a list of all the currently supported models [here](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/download_model_weights.md)

And we'd be happy to accept contributions for other large-scale models. Please feel free to re-open this issue if you have any follow up questions.
