### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by TheGermanEngie** [Lightning-AI/litgpt#1227]
Continuing off issue #861 where a path problem has turned into a data loading problem. Opened a new lightning-ai studio instance, freshly installed the repo and downloaded the checkpoint, still same error. 

<img width="946" alt="Screenshot 2024-04-01 at 18 50 18" src="https://github.com/Lightning-AI/litgpt/assets/75632861/cc571f56-9fcc-4ba7-b24d-6157b8ff4f94">

Here is a sample of my dataset.

[sample.json](https://github.com/Lightning-AI/litgpt/files/14826554/sample.json)

**Comment by TheGermanEngie** [comment]
I even updated the dataset to have one more indent for the {} to match litgpt's given .json object formatting:

From this:
<img width="513" alt="Screenshot 2024-04-01 at 19 49 36" src="https://github.com/Lightning-AI/litgpt/assets/75632861/36c6f316-403d-4bce-bdaf-d0b28dbaede0">

To this:

<img width="527" alt="Screenshot 2024-04-01 at 19 49 57" src="https://github.com/Lightning-AI/litgpt/assets/75632861/edf5b708-6db2-463b-8b7f-a8a38c521345">

And I still get the same error.

**Comment by TheGermanEngie** [comment]
Running a test load of the default Alpaca dataset with the command `litgpt finetune lora --data Alpaca --checkpoint_dir checkpoints/mobiuslabsgmbh/aanaphi2-v0.1` runs fine, so I think it's my dataset. I can't find any formatting differences between the default dataset and mine, so kind of at a loss here.

**Comment by TheGermanEngie** [comment]
I would like to add that my dataset does exponentially grow in size because it is based around a speaker diarization type of dataset. To keep all the context of the conversation, each time the Speaker 0 and Speaker 1 nametags change in the dataset, the output is loaded back into the "input" format and the text continues until Speakers change, for example:

<img width="1103" alt="Screenshot 2024-04-01 at 20 35 17" src="https://github.com/Lightning-AI/litgpt/assets/75632861/a5a1eb32-0568-4e8a-9ab8-41dedcb7fc50">

As you can imagine, it grows very exponentially. This makes me wonder if the error earlier has to do with context length limits or anything like that when initially loading the dataset: as the finetuning scripts work by`determining the size of the longest tokenized sample in the dataset to determine the block size.`and the files do get quite long. I also did try to truncate the dataset earlier with `--train.max_seq_length 256` to no difference.

**Comment by gitgroman** [comment]
Same for me, I don't think size matters as it failed with really small dataset with few records.

**Comment by carmocca** [comment]
@rasbt can you check this out? There might be a bug in the json datamodule

**Comment by carmocca** [comment]
#1241 improves the messaging
