### ISSUE TITLE
Categorize SFT and Pretraining data

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1243]
Ideally we only want the SFT finetuning datasets to show up in `litgpt finetune --help` and only the pretraining datasets to show up in `litgpt pretrain --help`. 

I believe we were thinking about that a while back but there was no good way to do that with jsonargparse. I am opening this issue so we don't forget to revisit this someday.

**Comment by carmocca** [comment]
Isn't this a duplicate of https://github.com/Lightning-AI/litgpt/issues/1084 of yours?

**Comment by carmocca** [comment]
Note that this needs to be done by having two different base classes and having the files use only one of them in their type signatures

**Comment by rasbt** [comment]
We can close this as duplicate.
