### ISSUE TITLE
Question about using custom dataset for pretraining

### ISSUE THREAD

**Issue by TonAnh** [Lightning-AI/litgpt#1256]
Hi, I already read the tutorial about "Pretrain TinyLlama" but still confuse about how to use my own custom dataset for pretraining.

As I understand, I need to follow these step:
1. Download my raw custom dataset
2. Write the "prepare" script for the dataset in `litgpt/data` to process and have a `*.bin` of the dataset

But:
- Do I need to modify the file `litgpt/data/tinyllama.py`? 
- What if I want to run pretraining on different model than TinyLlama? Can I run the command like this?

```
litgpt pretrain \
  --model_name Mistral-7B-v0.1 \
  --data path-to-my-dataset \
  --tokenizer_dir checkpoints/mistralai/Mistral-7B-v0.1
```

Thank you very much!

**Comment by rasbt** [comment]
Hi there, 
your overall process sounds correct to me. There's a `LitData` module by Adrian that you can use for a preprocessed datasets via `--data LitData <path>`.

In addition, there is also a `TextFiles` class in the works via #1235 to preprocess a folder of text files, and then use the preprocessed files for pretraining. I would only recommend this for smaller datasets though, not if you have hundreds of gigabytes of data.

In any case, maybe the updated (WIP) pretraining doc is helpful as it also contains links to project templates:

https://github.com/Lightning-AI/litgpt/blob/50e05de2acbbca067f571cc0adec59a977c8da33/tutorials/pretrain.md

Let me know if you have any feedback about the doc so we can address it in #1235 for others as well

**Comment by TonAnh** [comment]
Hi, thank you. 

I think the updated Pretraining Doc could be better if the Warning section you guys could specify the syntax when using LitData likes you said above  `--data LitData --data.path path/to/your/data` because I would be mistaken that the path of LitData would be the same as TextFile like this `--data LitData --data.train_data_path my_data_path`

**Comment by rasbt** [comment]
Thanks for the note. I agree that we should document this better!
