### ISSUE TITLE
Deployment example

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#1259]
It's not clear to users how they would take a trained LitGPT model and deploy it. There are of course 100 ways to do that but maybe we could have one standard example. 

We have a conversion tutorial here
https://github.com/Lightning-AI/litgpt/blob/main/tutorials/convert_lit_models.md#a-finetuning-and-conversion-tutorial
but it stops there. We also have several Studios but it's not clear which one to use as a template.

**Comment by rasbt** [comment]
I'll try to expand on that, maybe it could be based on LitServe

**Comment by rasbt** [comment]
This was addressed in #1299
