### ISSUE TITLE
Feature Request: A generation API that does not load the model weights every time

### ISSUE THREAD

**Issue by codamin** [Lightning-AI/litgpt#1263]
#### Requested Feature
It would be very convenient if there was a generation API which did not load the model weights for every generation call. Using the current ```litgpt.generate.base``` script, the model is loaded every time, which is time-consuming.

#### My current workaround
For now, I am manually removing the prompt tokenization prompt from the ```litgpt.generate.base.main()``` and make it a separate function which is called every time, as opposed to the rest of ```litgpt.generate.base.main()``` which is called only once.

**Comment by rasbt** [comment]
Thanks for the suggestion. Actually, I think the `litgpt chat` API might be exactly what you are looking for. Maybe give it a try and let us know if it addresses your use case.

**Comment by codamin** [comment]
Thanks a lot for your response. Indeed, you are right, ```chat``` mode is exactly what I needed. I used to think that ```chat``` mode was for ```multi-hop conversation``` and therefore not a series of independent prompt→generations.

**Comment by rasbt** [comment]
Oh nice, glad it addresses your usecase already. And I totally agree, the name `chat` is a bit misleading here. I think the original plan was to add a setting for multi-hop (e.g. `multiturn=True`) but haven't had the chance to add it yet.
