### ISSUE TITLE
argument subcommand: invalid choice: 'evaluate'

### ISSUE THREAD

**Issue by Gooooooogo** [Lightning-AI/litgpt#1268]
when I run:
'litgpt evaluate --checkpoint_dir checkpoints/microsoft/phi-2/ --batch_size 4 --out_dir evaluate_model'

It has a problem:
Error: argument subcommand: invalid choice: 'evaluate' (choose from 'download', 'chat', 'finetune', 'pretrain', 'generate', 'convert', 'merge_lora')

**Comment by rasbt** [comment]
Hm, that's a weird one. I am wondering if you are perhaps using an older version of litgpt? Because `evaluate` was just added last week.

**Comment by rasbt** [comment]
Just following up on this, have you been able to run it?

Until the PyPI package is updated in the next few days, I recommend installing it from the GitHub repository directly:

```bash
git clone https://github.com/Lightning-AI/litgpt
cd litgpt
pip install -e '.[all]'
```

Please let us know in case there are any follow up questions or issues.
