### ISSUE TITLE
error: Unrecognized arguments: --val_split_fraction 0.1

### ISSUE THREAD

**Issue by Magniveo** [Lightning-AI/litgpt#1288]
I cloned the repository and built it, but when I ran the command to
`litgpt finetune lora --checkpoint_dir checkpoints/microsoft/phi-2 --data JSON --data.json_path my_custom_dataset.json --val_split_fraction 0.1 --out_dir out/phi-2-lora` I encountered an error `error: Unrecognized arguments: --val_split_fraction 0.1`
What I doing incorrect?

**Comment by Moon-Ahn** [comment]
same problem

**Comment by carmocca** [comment]
It should be `--data.val_split_fraction 0.1`

Could you open a PR fixing it?

**Comment by Magniveo** [comment]
ok, but i have another problem on download checkpoints/microsoft/phi-2,  Permission error: [WinError 5]

**Comment by rasbt** [comment]
Arg, yes, this should be `--data.val_split_fraction 0.1`. 

Regarding the permission error: That's a weird one. Could you try to create the folders manually before trying `litgpt download --repo_id microsoft/phi-2`. I believe on Windows that's `mkdir checkpoints\microsoft\phi-2
`.

Btw a PR to fix the `--data.val_split_fraction 0.1` would be appreciated. But I am also happy to do it, just let me know.

**Comment by Magniveo** [comment]
Problem with second tensor file. I have only one bin file.

**Comment by williamFalcon** [comment]
closed by #1295
