### ISSUE TITLE
tokenizer.py

### ISSUE THREAD

**Issue by fireyanci** [Lightning-AI/litgpt#1333]
Due to meta-ai lama-3-8b not using sentencePiece, but litgpt/tokenizer. py still uses sentencePiece. When I use the litgpt chat -- checkpoint_dir E: \ checkpoint \ meta llama \ Meta-Llama-3-8B Instrument
RuntimeError: Internal: could not part ModelProto from E: \ checkpoint \ meta llama \ Meta Llama-3-8B Instrument \ tokenizer. model
How to solve it

**Comment by rasbt** [comment]
Hi there,
thanks for reporting this. If the Hub does not provide a `tokenizer.model` file, it should use the `tokenizers` library instead:

https://github.com/Lightning-AI/litgpt/blob/63a0a10f30a92b317cbd3ea40fc61e15af2b0858/litgpt/tokenizer.py#L21-L33

In the case of Llama 3, only the `tokenizer.json` is provided, so it should not use sentencepiece:

<img width="1305" alt="Screenshot 2024-04-22 at 10 47 40 AM" src="https://github.com/Lightning-AI/litgpt/assets/5618407/50861556-e242-4910-a501-b614920c205a">

I was trying this in a fresh environment

```
git clone https://github.com/Lightning-AI/litgpt.git   
cd litgpt

pip install -e ".[all]"
litgpt download --repo_id meta-llama/Meta-Llama-3-8B-Instruct --access_token ...

pip uninstall sentencepiece 
litgpt chat --checkpoint_dir checkpoints/meta-llama/Meta-Llama-3-8B-Instruct 
```

and it worked without problem.

<img width="725" alt="Screenshot 2024-04-22 at 10 45 29 AM" src="https://github.com/Lightning-AI/litgpt/assets/5618407/df4bcb65-8608-4e42-a163-2e4c79f1f2af">


I was using tokenizers version '0.19.1', perhaps you have an older version installed? Could you try to upgrade it via 
`pip install tokenizers -U` and give it another try?

**Comment by rasbt** [comment]
Let us know if you still have problems here, happy to reopen and revisit!
