### ISSUE TITLE
test_tinyllama issue with LitData and `iterate_over_all`

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/litgpt#1399]
Hi there 👋 

Apparently there is an [issue](https://github.com/Lightning-AI/litgpt/actions/runs/8988120774/job/24722301419#step:6:1224) with tinyllama test and the newest version of LitData (0.2.6).
In the [release notes](https://github.com/Lightning-AI/litdata/releases/tag/v0.2.6) one can see that `iterate_over_all` has just been added:
> Add support for iterate_over_all for the CombinedDataset by @tchaton in https://github.com/Lightning-AI/litdata/pull/122

and that's why the issue didn't appear before.

Don't know whether this issue is on LitGPT or LitData side.
Maybe @awaelchli has any thoughts?

**Comment by awaelchli** [comment]
LitData made the decision to enforce `iterate_over_all` by default as a breaking change. LitGPT will have to set `iterate_over_all=False` explicitly now and require `litdata>=0.2.6`. The error message should be fixed though.

**Comment by tchaton** [comment]
Yes, the default behaviour was confusing to some users. It felt more natural all the samples should be seen, especially when used for computing the validation metrics.

As @awaelchli shared, let's add `iterate_over_all` to LitGPT where needed.
