### ISSUE TITLE
Remove old and unused LLMs

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1401]
Following up on a request, we may want to prune a few models that are not really used in practice anymore from LitGPT to declutter.

If I were to remove LLMs, my candidates would be:

- Dolly
- Nous-Hermes
- Platypus
- RedPajama-INCITE
- Vicuna

Any thoughts or additional suggestions?

**Comment by harshil1973** [comment]
Can I work on this issue? Is it beginner-friendly?

**Comment by rasbt** [comment]
Yes, it should be relatively beginner friendly. Feel free to work on it.

**Comment by Sanjo17** [comment]
Can I work on this issue?

**Comment by ParagEkbote** [comment]
Could you please mark this issue as done @rasbt ?

**Comment by Andrei-Aksionov** [comment]
I'll close the issue.
Thanks @ParagEkbote for the PR.
