### ISSUE TITLE
Create new CI API key

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/litgpt#1433]
CI uses my personal API key for tests. A company-owned one should be used. This is the `HF_TOKEN` key in https://github.com/Lightning-AI/litgpt/settings/secrets/actions and `PYPI_API_TOKEN`

The HF key needs access to all the models available in [config.py](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/config.py).
Without it, the HF tests will be skipped. An example test is this: https://github.com/Lightning-AI/litgpt/blob/main/tests/test_tokenizer.py#L15-L16

**Comment by rasbt** [comment]
Thanks for the note, I will take care of it!
