### ISSUE TITLE
mistralai/Mistral-7B-v0.3 support

### ISSUE THREAD

**Issue by karkeranikitha** [Lightning-AI/litgpt#1444]
When will finetuning support for mistralai/Mistral-7B-v0.3 be integrated?

**Comment by rasbt** [comment]
Sorry, I don't have an ETA at the moment as there are some other things on the list first. By the way, I started it here #1431 but then noticed that there are some new weights (or weight naming conventions) compared to v0.2 that I'd have to look into further to make it work.

**Comment by karkeranikitha** [comment]
ok thank you.

**Comment by davmacario** [comment]
> noticed that there are some new weights (or weight naming conventions) compared to v0.2

I did notice that too! It is strange, though, as the 'model.safetensors.index.json' file in the [huggingface repo](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/blob/main/model.safetensors.index.json) uses the usual weight names...

**Comment by davmacario** [comment]
@rasbt One other thing I noticed is that if the downloading script decides to use Safetensors, it will not download the 'model.safetensors.index.json', as its name does not match `"*.safetensors"`, as specified at [this line](https://github.com/Lightning-AI/litgpt/blob/ee9108f6608e71cdfe494848a9b63451b2ef1cc1/litgpt/scripts/download.py#L62).

Shouldn't that line contain:
```python
download_files.append("*.safetensors*")
```
instead (similarly to what done if downloading `.bin` files [here](https://github.com/Lightning-AI/litgpt/blob/ee9108f6608e71cdfe494848a9b63451b2ef1cc1/litgpt/scripts/download.py#L58)), or is that the desired behavior?

I can put together a tiny PR if needed :)
