### ISSUE TITLE
Continue finetuning

### ISSUE THREAD

**Issue by SergioG-M** [Lightning-AI/litgpt#1464]
Is it possible to continue the finetuning of an already finetuned model?

Let's say that I finetune a model for 1 epoch with lora, is it possible to take those weights (maybe with merge_lora first?) and finetune for another epoch?

**Comment by rasbt** [comment]
Yes, this is possible, and I remember doing it in the past. You can use the `out_dir` of one LoRA run as the input for the next run.

**Comment by SergioG-M** [comment]
Yes, it is possible with the merged model, at least with Lora (perhaps not with the adapter).
