### ISSUE TITLE
Support non-int batch_size argument "auto" with litgpt evaluate

### ISSUE THREAD

**Issue by ebektas** [Lightning-AI/litgpt#1467]
I use lm_evals "batch_size auto:N" for dynamically deciding batch_size. As far as I understand I can't pass auto to lm_eval through litgpt.

```bash
litgpt evaluate --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-Chat-v1.0 \
--batch_size auto \
--tasks "hellaswag,truthfulqa_mc2,mmlu" \
--out_dir evaluate_model/
```

```bash
usage: litgpt [options] evaluate [-h] [-c CONFIG] [--print_config[=flags]] --checkpoint_dir CHECKPOINT_DIR [--tasks TASKS] [--out_dir OUT_DIR]
                                 [--force_conversion {true,false}] [--num_fewshot NUM_FEWSHOT] [--batch_size BATCH_SIZE] [--device DEVICE]
                                 [--dtype.help CLASS_PATH_OR_NAME] [--dtype DTYPE] [--limit LIMIT] [--seed SEED] [--save_filepath SAVE_FILEPATH]
error: Parser key "batch_size":
  Expected a <class 'int'>. Got value: auto
```

**Comment by ebektas** [comment]
Thank you for the quick response and thanks for letting me know, I'll be
updating my version.

Not to be too nit picky but it is something I use 🙃 lm_eval accepts
batch_size in the form of "auto:N" also, auto for checking how many batches
will fit and :N for how many times to check.
"batch_size !=auto" in the PR looks like will prevent that from passing
through.
https://github.com/EleutherAI/lm-evaluation-harness/tree/main?tab=readme-ov-file#user-guide

Happy to see litgpt expanding with eval & serve and making the CLI very
friendly to use!
Regards

Sebastian Raschka ***@***.***>, 7 Haz 2024 Cum, 18:35
tarihinde şunu yazdı:

**Comment by rasbt** [comment]
Thanks for the follow-up. I should have waited with merging ... but I hope #1470 addresses it now!
