### ISSUE TITLE
Command -> litgpt download openlm-research/open_llama_13b gives error: Unrecognized arguments: openlm-research/open_llama_13b

### ISSUE THREAD

**Issue by VamsiYK** [Lightning-AI/litgpt#1471]
⚡ ~ litgpt download openlm-research/open_llama_13b
usage: litgpt [options] download [-h] [-c CONFIG] [--print_config[=flags]] [--repo_id REPO_ID] [--access_token ACCESS_TOKEN]
                                 [--tokenizer_only {true,false}] [--convert_checkpoint {true,false}] [--dtype DTYPE]
                                 [--checkpoint_dir CHECKPOINT_DIR] [--model_name MODEL_NAME]
error: Unrecognized arguments: openlm-research/open_llama_13b

**Comment by rasbt** [comment]
We recently updated the CLI, and it looks like the LitGPT version you are using requires the old `--checkpoint_dir`. I can make a new version release today for PyPI to address that. In the meantime, please upgrade LitGPT by

```bash
pip install litgpt==0.4.0.dev0
```

Let me know if it works or doesn't work.

**Comment by VamsiYK** [comment]
Yeah it is working , One more issue is when running this -> `i# 3) Use the server (in a separate session)
import requests, json
response = requests.post(
     "http://127.0.0.1:8000/predict",
     json={"prompt": "Why people don't check cctv footage of all poling booths in INDIA to check if any malpractices occured? Is this not a big threat to democracy? "}
)
print(response.json())` am getting output as "{'detail': 'Request timed out'}"

**Comment by rasbt** [comment]
Please feel free to report back and reopen if the issue still persists.
