### ISSUE TITLE
Finetuning with multiple gpus extemely slow

### ISSUE THREAD

**Issue by SergioG-M** [Lightning-AI/litgpt#1472]
Hi, I finetuned a Falcon-7B on one GPU (A10 G) with LoRA, and it was reasonably fast, with an iteration time of approximately 100 ms.

![image](https://github.com/Lightning-AI/litgpt/assets/61322372/96320acb-7a88-40e2-bdcd-e862e2651729)

I tried the same with 8 GPUs, using the same configuration, and it is super slow, with an iteration time of 30 seconds! I guess this is not normal. Do you have any idea what may be happening?

![image](https://github.com/Lightning-AI/litgpt/assets/61322372/11ac0a8c-c5db-4e8e-9a4f-752ce7ae9670)

My end goal is to finetune a Falcon-40B, but I won't be able to do it at these speeds.

**Comment by SergioG-M** [comment]
Ok, It wasn't a problem of the FSDP but of the machine (sagemaker) that I was using, with low inter-gpu speed.

**Comment by rasbt** [comment]
Glad to hear that you were able to resolve it and it wasn't a bug in litgpt in your case :)
