### ISSUE TITLE
Add Gemma 2 Checkpoints

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1535]
Gemma 2 checkpoints are out: https://x.com/clmt/status/1806342399347597589

Haven't had a chance to look into these, but hopefully they are not too different from Gemma 1 in terms of custom architecture components.

**Comment by Andrei-Aksionov** [comment]
I have a feeling that it won't be a smooth sailing 😉 

When the code is strange
And the documentation is weak
Who are you gonna call?
~Ghostbusters~
