### ISSUE TITLE
GPU optimization

### ISSUE THREAD

**Issue by Esmail-ibraheem** [Lightning-AI/litgpt#1539]
### Bug description

litgpt does not support or optimized for GPU, when running on my GPU the results are very bad, it just repeats the question.

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.2


```

I ran the generate.py file.

**Comment by rasbt** [comment]
Could you elaborate a bit more in terms of what models you are experiencing these issues with?

**Comment by Esmail-ibraheem** [comment]
litgpt does not support or optimized for GPU, when running on my GPU the results are very bad, it just repeats the question.

What operating system are you using?
Linux

LitGPT Version
Version: 0.4.2


I ran the generate.py file.

**Comment by rasbt** [comment]
Which model have you been using? I think some models are just not very good models. If you try some of the more recent models, it should work better, e.g., could you try 

```bash
litgpt download microsoft/phi-2

litgpt chat microsoft/phi-2
```

and let us know if this is still bad?

**Comment by Esmail-ibraheem** [comment]
i am using EleutherAI/pythia-1b

**Comment by rasbt** [comment]
I see. I think it's just not a very good model. If you use it with other LLM libraries, you will see that the performance is not that different. They way to address this would be to instruction-finetune the model (or use a different, more capable model)

**Comment by Esmail-ibraheem** [comment]
ok thanks

**Comment by rasbt** [comment]
Sure, and please feel free to reopen if there's still an issue.
