### ISSUE TITLE
not quite good results.

### ISSUE THREAD

**Issue by Esmail-ibraheem** [Lightning-AI/litgpt#1540]
### Bug description

when i am running generate.py file on the checkpoint_dir = Path("checkpoints") / "EleutherAI" / "pythia-1b" checkpoints, the results in linux is good but it repeats the answer like that: 

```
What food do llamas eat?

Llamas eat a lot of things. They eat grass, and they eat bark, and they eat leaves. They eat nuts, fruits, seeds, and everything else.

What do llamas eat?

Llamas eat grass, bark, leaves, and nuts. They eat grass, bark, leaves, and nuts. They eat grass, bark, leaves, and nuts. They eat grass, bark, leaves, and nuts. They eat grass, bark, leaves
```

in the other hand, in windows, the results not that quite good, the output as follows: 

```
What food do llamas eat?

Llamas eat a lot of things. They eat grass, hay, fruit, and seeds. They eat what they eat. If they eat grass, they eat grass. If they eat hay, they eat hay. If 
they eat fruit
```

### What operating system are you using?

Linux

### LitGPT Version

``` 

Version: 0.4.2

```

**Comment by rasbt** [comment]
Hi there, and thanks for reporting. I would say this is expected because it's a small pretrained (not finetuned) base model. This sort of repetition is quite common especially for older models.

**Comment by Esmail-ibraheem** [comment]
Okay, but I have a question about continued pre-training. I want to pre-train the model on a large Arabic dataset (96GB). Can I do this using the instructions you provided in the continued pre-training section of the README?

and thank you.

**Comment by rasbt** [comment]
Yes, you could try that. But I think the tokenizers may not be ideal for that. I am not sure in how far they support Arabic letters and words. You could try the Gemma tokenizer, which has been trained for a 256k vocabulary that maybe supports those.

**Comment by Esmail-ibraheem** [comment]
Okay, thanks. But can you send me a link or any other information about the Gemma tokenizer?
