### ISSUE TITLE
add special tokens

### ISSUE THREAD

**Issue by shunlinlu** [Lightning-AI/litgpt#1543]
Hi,

How can I add special tokens? just like adding token functions in hugging face tokenizer.

Shunlin

**Comment by Andrei-Aksionov** [comment]
Hello @shunlinlu 

If `tokenizer.json` file is in the checkpoint directory, then as a processor [Tokenizers](https://github.com/huggingface/tokenizers) by HuggingFace is used (the same that is used inside HF AutoTokenizer).
https://github.com/Lightning-AI/litgpt/blob/0663b470ed21024b99c7cd515f98b411d6041349/litgpt/tokenizer.py#L22-L25

That means that it supports [`add_special_tokens`](https://huggingface.co/docs/transformers/en/main_classes/tokenizer#transformers.PreTrainedTokenizer.add_special_tokens) method. 
But you have to extend the logic in `litgpt/tokenizer.py` to your needs.

**Comment by shunlinlu** [comment]
Thanks.
