### ISSUE TITLE
Deal with warnings during model download and conversion

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/litgpt#1557]
When we download (and automatically convert) a model, we have these three warnings:
1. .../huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
2. .../huggingface_hub/file_download.py:1194: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
3. [W init.cpp:1436] Warning: write_record(): Passing Storage by data pointer is deprecated and will be an error in the future, please pass the Storage object instead. (function operator())

First two come during weights downloading, while the third - during conversion.

**Comment by rasbt** [comment]
Good call. I can take care of these next week

**Comment by Andrei-Aksionov** [comment]
It's not super-urgent, so maybe let's give the community a chance.
I think it's a cool thing when there are a number of `good first issue` issues, so it's easier to start contributing.
Other issues are quite technical, and it might be overwhelming for someone.
I started contributing by just providing annotations 😉.

**Comment by rasbt** [comment]
Good point, I agree

**Comment by bhargavyagnik** [comment]
This Issue has been solved, I think we can close it.

**Comment by rasbt** [comment]
Good point. Thanks again for the contribution!

**Comment by bhargavyagnik** [comment]
Anytime! I would love to contribute more and will keep an eye on the issues page for more contributions! If you have any, let me know. Thanks
