### ISSUE TITLE
Using litgpt.generate.tp for multi-GPU inference is nearly 2 times slower than single-GPU inference with litgpt.generate.base Description

### ISSUE THREAD

**Issue by kstanghere** [Lightning-AI/litgpt#1581]
### Bug description

While conducting inference on 1000 data samples using phi-mini-4k, I discovered that using litgpt.generate.tp for 2-GPU inference is nearly 2 times slower than single-GPU inference with litgpt.generate.base. This communication latency seems excessively high.

### What operating system are you using?

Linux

### LitGPT Version

``` 



```

**Comment by rasbt** [comment]
Hi there, and thanks for reporting. I wonder if this is perhaps due to a small GPU interconnect problem (related to #1577). Would you mind sharing the output from the `nvidia-smi topo -m` command?

**Comment by kstanghere** [comment]
> Hi there, and thanks for reporting. I wonder if this is perhaps due to a small GPU interconnect problem (related to #1577). Would you mind sharing the output from the `nvidia-smi topo -m` command?

Hi, thanks for your reply. Below is the output from the `nvidia-smi topo -m` command:
| | GPU0 | GPU1 | GPU2 | GPU3 | CPU Affinity | NUMA Affinity | GPU NUMA ID |
|---|---|---|---|---|---|---|---|
| GPU0 | X | NODE | SYS | SYS | 0-15,32-47 | 0 | N/A |
| GPU1 | NODE | X | SYS | SYS | 0-15,32-47 | 0 | N/A |
| GPU2 | SYS | SYS | X | NODE | 16-31,48-63 | 1 | N/A |
| GPU3 | SYS | SYS | NODE | X | 16-31,48-63 | 1 | N/A |

Legend:

- X    = Self
- SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI) 
- NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
- PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
- PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
- PIX  = Connection traversing at most a single PCIe bridge
- NV#  = Connection traversing a bonded set of # NVLinks

**Comment by rasbt** [comment]
Thanks for sharing, in this case it does look like it's because the GPUs are connected with a slow connection, unfortunately. Ideally to get a better speedup, you'd need to have NV connections.

**Comment by kstanghere** [comment]
> Thanks for sharing, in this case it does look like it's because the GPUs are connected with a slow connection, unfortunately. Ideally to get a better speedup, you'd need to have NV connections.


Thanks for the clarification. However, I'm puzzled by the fact that when I use `deepspeed-inference` for multi-GPU inference, the communication latency doesn't seem to be as high as when using `litgpt.generate.tp`. Is that normal?

**Comment by rasbt** [comment]
Good question, and I am not sure. We used to use DeepSpeed at the very beginning of this project but then changed it to PyTorch's native multi-GPU strategies. It could be that they have more communication overhead, but since DeepSpeed is currently not supported in LitGPT I don't have a side-by-side comparison.

**Comment by kstanghere** [comment]
> Good question, and I am not sure. We used to use DeepSpeed at the very beginning of this project but then changed it to PyTorch's native multi-GPU strategies. It could be that they have more communication overhead, but since DeepSpeed is currently not supported in LitGPT I don't have a side-by-side comparison.

Thanks for your explanation and I will close the issue.  I understand that without direct side-by-side comparison, it's difficult to pinpoint the exact reasons for the differences in communication overhead.  Your work on LitGPT is valuable to the community, and I look forward to seeing how it evolves :)
