### ISSUE TITLE
API has confusing/wrong description

### ISSUE THREAD

**Issue by MaxGonzalezSaez-Diez** [Lightning-AI/litgpt#1608]
### Bug description

Class LLM in[ litgpt/api.p](https://github.com/Lightning-AI/litgpt/blob/2104b5b5b688666246357ca0aa3890f73e7ff6ba/litgpt/api.py#L185C9-L185C21)y has argument `prompt` which according to the function signature is a `str`. However in the docstrings prompt is a tensor apparently. Line 217 calls prompt_style apply so this indicates that the docstrings are not updated. 

This is confusing. In the Readme/Tutorial files, the api is always used by first calling prompt_style before passing that to the .generate function. This indicates that prompt_style is being applied twice (which isnt great  if during training prompt_style has been applied only once.)

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.3
```

**Comment by rasbt** [comment]
Thanks a lot for the note. I think this was just a docstring issue (just fixed it).

The generate function itself does not apply the `prompt_style` unless I am overlooking something. The prompt style in generate would only be applied if you use the `main` function, which is what's used when you use `litgpt generate`:

https://github.com/Lightning-AI/litgpt/blob/1ede90dc281e60ff963bbfea345e998a358082be/litgpt/generate/base.py#L228

 the API is using `generate` function in that file.

Please feel free to reopen, it's possible that I am not seeing it correctly. In any case, thanks for raising that!
