### ISSUE TITLE
about litgpt command

### ISSUE THREAD

**Issue by aekx** [Lightning-AI/litgpt#1689]
Can I perform fine-tuning using litgpt/finetune/lora.py instead of using the litgpt finetune command?

**Comment by aekx** [comment]
Thank you for your previous response. I encountered an issue while running litgpt/finetune/lora.py. Could you please advise what the input for the data parameter should be? For instance, I have a data folder with train.json and val.json files under it.

**Comment by rasbt** [comment]
For a JSON file, you can follow the following example:

```python
curl -L https://huggingface.co/datasets/ksaw008/finance_alpaca/resolve/main/finance_alpaca.json -o my_custom_dataset.json

litgpt finetune_lora microsoft/phi-2 \
  --data JSON \
  --data.json_path my_custom_dataset.json \
  --data.val_split_fraction 0.1 \
  --out_dir out/custom-model
```

Note that there is currently no option to provide a separate JSON file as validation data; the validation potion is taken from the input dataset (the ratio of training and validation data is determined via `--data.val_split_fraction 0.1`)

I hope this helps!
