### ISSUE TITLE
grokadamw and 8bit bnb optimizers

### ISSUE THREAD

**Issue by mtasic85** [Lightning-AI/litgpt#1743]
Hi everyone,

I wondering how to use optimizers such as [grokadamw](https://github.com/cognitivecomputations/grokadamw) and AdamW8bit.

When I try to use them I get error:

```
TypeError: AdamW8bit.__init__() got an unexpected keyword argument 'fused'
``` 

'fused' is always passed as argument to optimizer.

**Comment by rasbt** [comment]
Hi there,

theoretically other optimizers that have a PyTorch optimizer-like usage should work, I think. Here's how the optimizer is instantiated:

https://github.com/Lightning-AI/litgpt/blob/be8b28dad46caee5dd62fedcd6051485e27c404b/litgpt/utils.py#L559-L567

I only tested it with Adam and SGD optimizers though, which have the "fused" parameter. I think this should be updated to support other optimizers as well (a good test case would be `torch.optim.RMSprop`, which doesn't have a `fused` parameter).

**Comment by mtasic85** [comment]
I think this line causes issue:

https://github.com/Lightning-AI/litgpt/blob/be8b28dad46caee5dd62fedcd6051485e27c404b/litgpt/pretrain.py#L212

It assumes that `'fused'` should be `True` if `cuda` is present.

**Comment by rasbt** [comment]
Good catch. Tbh I only checked the lora and full finetuning codes which is probably why I missed this. Ideally this could be updated to only provide these extra_args the chosen optimizer has the `fused` parameter.

**Comment by rasbt** [comment]
Yes, a `'fused' in inspect.signature(optimizer)` check sounds totally reasonable. Please feel free to add this via a PR if you have time.
