### ISSUE TITLE
How to set seed when generation outputs are not the same everytime?

### ISSUE THREAD

**Issue by mrpeerat** [Lightning-AI/litgpt#1757]
Hi,

Here is my code
```
from litgpt import LLM
llm = LLM.load("out/finetune/qlora-gemma-7b/step-000800")
text = llm.generate("Recommend a movie",max_new_tokens=100,temperature=1)
print(text)
```
When I ran it 3 times, it got me a different answer everytime. 
How do you set the seed or temperature so that the model answers the same every time for the same prompt?

Thank you.

**Comment by rasbt** [comment]
You could set

```bash
text = llm.generate("Recommend a movie", temperature=0., top_k=1)
```

Let me know in case this doesn't work or if you have follow-up questions.

**Comment by Andrei-Aksionov** [comment]
Fixing seed and setting temperature to 0 are not the same 🙂.

What's interesting, is that we set seed in 

https://github.com/Lightning-AI/litgpt/blob/e7e8f7cfe5c1ca93660934ef3789109f17c72480/litgpt/generate/base.py#L506

**Comment by rasbt** [comment]
Oh I see what you mean. Yeah, if you want sampling, but still deterministic behavior via a seed, you can set it manually via

```
torch.manual_seed(0)
llm.generate("what do llamas eat?")

torch.manual_seed(0)
llm.generate("what do llamas eat?")

torch.manual_seed(0)
llm.generate("what do llamas eat?")
```

This will then always generate the same response.

> What's interesting, is that we set seed in

Yeah, it's interesting that this still results in non-deterministic behavior
