### ISSUE TITLE
invalid decimal literal?

### ISSUE THREAD

**Issue by hemanth** [Lightning-AI/litgpt#1758]
<img width="478" alt="image" src="https://github.com/user-attachments/assets/1aa4457d-2230-4b68-aeaa-f7b5251039f8">

**Comment by rasbt** [comment]
Hi there, it looks like you are running a terminal command in a Jupyter notebook. To make this work, you'd have to prepend an exclamation mark. E.g. `!litgpt finetune_lora ...`. Let me know in case this still doesn't work.

**Comment by hemanth** [comment]
Ah! Righto. One of the `readme.ipynb` needs a fix.
