### ISSUE TITLE
Changing default activation function

### ISSUE THREAD

**Issue by mtasic85** [Lightning-AI/litgpt#1761]
How can activation be changed. For example `'gelu'`, `'silu'` (used by mistral, llama3, qwen2), `'relu'` (I know it is not good choice, but sometimes for testing purposes should be fine)?

If it can be changed does it only apply to MLP?

**Comment by rasbt** [comment]
Yes I think you should be able to change it without issue because it doesn't change the number of parameters in the models. You should be able to make that change directly in the `model.py` file (https://github.com/Lightning-AI/litgpt/blob/main/litgpt/model.py)

**Comment by mtasic85** [comment]
Thanks @rasbt . 

I found it: https://github.com/Lightning-AI/litgpt/blob/e7e8f7cfe5c1ca93660934ef3789109f17c72480/litgpt/model.py#L373

Since config is available, it could be good if this can be configurable. I know it is not by official documentation/specification by allows some experimentation. Even better it might be possible to compose MLP directly from config file. What do you think?

It is far fetch, maybe whole model could be composable via configuration in future. All building blocks are already there. It is easier to have config file than for of litgpt for each model arch.

It turned out that litgpt is easier to work with and experiment than anything else I have tried so far.

**Comment by rasbt** [comment]
Thanks for suggesting. I generally like the idea of making it more configurable, but I had a discussion about something related with my colleagues a while back, and the goal would be to make the config file simpler rather than more complicated. I.e there are already too many bells and whistles for regular users. Thanks for suggesting though.

**Comment by mtasic85** [comment]
IMO good default values in config equals simpler config. This way, users who know what they are doing will configure or extend whatever part they want.

Even better solution is to have something like `extend` (or `override`) statement at the beginning of user config file which will extend  predefined config file. This way litgpt team can prefine all models, and allow user just to configure parts they want. Everything is explicit in config files, so no need to read python files to double check what are default values.

**Comment by rasbt** [comment]
I don't disagree here but it would also mean that it would increase the complexity of the model.py file. One of the goals of this project was to keep it as lean as possible. I think config settings are good but for customization such as these it would get quickly out of hand in terms of complexity for architecture customizations.

**Comment by rasbt** [comment]
Maybe a good rule of thumb would be to keep the config files focused on hyperparameters (and general settings like file paths etc) whereas any non-standard changes like architecture customizations could be made in the model.py file directly (I'd say this is only something researchers or developers of new architectures would do, and this why we want to keep the model.py small and lean to make customizations somewhat easy to do in the file directly.)
