### ISSUE TITLE
prompts.py and "evaluating on a custom test set" section in the model evaluation tutorial

### ISSUE THREAD

**Issue by zty12713** [Lightning-AI/litgpt#1778]
In [this section](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/evaluation.md#evaluating-on-a-custom-test-set) in the tutorial, after applying the Alpaca prompt style on the data sample, all the contents of the data sample including "output" are in the formatted string under "Instruction." Since this formatted prompt is later fed to the LLM, isn't it concerning that the correct output itself is in the prompt? Is it a bug in the implementation in [prompts.py](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/prompts.py)? From the code of Alpaca class there, it seems only the "instruction" part in the data sample should be put under "Instruction" in the formatted prompt.

Furthermore, is prompts.py used in the finetuning? If so, would it be very concerning as LLMs would be finetuned to get used to having the correct response in the prompt?

**Comment by zty12713** [comment]
To answer my own question "Is it a bug in the implementation in [prompts.py](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/prompts.py)?" it is more of an issue of how prompt_style.apply() is called in the example from the tutorial. Specifically, instead of 
```python
from litgpt.prompts import Alpaca

prompt_style = Alpaca()
prompt_style.apply(test_data[0])
```
this should return a more expected and appropriate formatted prompt
```python
from litgpt.prompts import Alpaca

prompt_style = Alpaca()
prompt_style.apply(prompt=test_data[0]["instruction"], **test_data[0])
```
which is

```
"Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nName the author of 'Pride and Prejudice'.\n\n### Response:\n"
```
Still, I'd like to know if the apply() method of any prompt styles is incorrectly called in any other places, especially in finetuning code. Thank you!

**Comment by rasbt** [comment]
Hi @zty12713 , thanks for opening this issue. You are right, this is indeed a typo in the evaluation tutorials. I am fixing it in #1790 

In the finetuning code, it looks like it's correctly called:

https://github.com/Lightning-AI/litgpt/blob/a66dcc9876d185835796d3d2ff6c8f3e11a355b2/litgpt/finetune/full.py#L333C1-L337C50
