### ISSUE TITLE
finetune with lora tutorial error

### ISSUE THREAD

**Issue by micrem73** [Lightning-AI/litgpt#1797]
Hi,

in the tutorial page https://github.com/Lightning-AI/litgpt/blob/main/tutorials/finetune_lora.md#tune-on-your-dataset , the command to finetune a model with lora is:

litgpt finetune_lora stabilityai/stablelm-base-alpha-3b \
  --data Alpaca

However, when running the command I get this error:

usage: litgpt [-h] [-c CONFIG] [--print_config[=flags]]
              {download,chat,finetune,pretrain,generate,convert,merge_lora,evaluate,serve} ...
error: argument subcommand: invalid choice: 'finetune_lora' (choose from 'download', 'chat', 'finetune', 'pretrain', 'generate', 'convert', 'merge_lora', 'evaluate', 'serve')

What's the correct syntax?

**Comment by rasbt** [comment]
I just gave it a try and it works fine for me. Do you perhaps have an older version of LitGPT installed? You can print the version via 

```python
pip list | grep litgpt
```

**Comment by micrem73** [comment]
Hi,

you were right, my installation was old. I upgraded and now it works.

cheers
michele

**Comment by rasbt** [comment]
Nice, glad to hear that it fixed it!
