### ISSUE TITLE
Question about loss calculated in finetuning

### ISSUE THREAD

**Issue by richardzhuang0412** [Lightning-AI/litgpt#1808]
When I am doing full finetuning with a dictionary-like dataset like {"instruction": xxx, "output": xxx}, is the loss calculated over output only or the whole concatenated sequence?

**Comment by rasbt** [comment]
It's the common supervised instruction finetuning (SFT) setup , i.e., all input and output tokens except for the prompt template tokens.

**Comment by richardzhuang0412** [comment]
Just to clarify, so if I put my input data into "instruction" key, it won't be incorporated when calculating the loss?

**Comment by rasbt** [comment]
Actually, let me take my response back. I was initially thinking of my book, where the instruction+input tokens are used by default and then masked as an optional exercise. Here, in LitGPT, we take an opposite approach and mask the prompt tokens by default unless you turn off the masking. So yes, you are correct.

You can see the relevant code here:

https://github.com/Lightning-AI/litgpt/blob/98ba29eded818ea9c000173c041a1f28cc327645/litgpt/data/base.py#L90-L91
