### ISSUE TITLE
Preicison none erronously always sets to 32-true

### ISSUE THREAD

**Issue by AurelioAguirre** [Lightning-AI/litgpt#1812]
### Bug description

In the api.py file starting from line 330:

        if precision is None:
            precision = get_default_supported_precision(training=False)
            precision = "32-true"

second precision assignment immediately overrides the first. This is a problem because quantization doesn't work unless precision is set to None.

Basically third line needs to be deleted. 

### What operating system are you using?

Unknown

### LitGPT Version

``` 

Version: 0.5.2


```

**Comment by rasbt** [comment]
Thanks for the note. This must have been a leftover from a debugging session. Fixing it now in #1814

**Comment by rasbt** [comment]
Should be fixed now!
