### ISSUE TITLE
fully fine-tuning specific set of layer

### ISSUE THREAD

**Issue by sorobedio** [Lightning-AI/litgpt#1813]
Hello, 

Could you guide me on how to fine-tune a specific set of layers of llama-3.2-1B-instruct on custom data, as specified in a YAML file, without using LoRA or QLoRA?

Thank you!

**Comment by rasbt** [comment]
Hi there,

the best way to go about that would be to modify the `finetune/full.py file`. Specifically, I would freeze the layers that you don't want to train after this line of code here:

https://github.com/Lightning-AI/litgpt/blob/ba4e92a7b56ddcbcc6326061f3b26db4484c1c0c/litgpt/finetune/full.py#L156

By freezing, I mean setting `requires_grad = False` for those layers you don't want to train.

**Comment by rasbt** [comment]
Closing but let me know in case you have any follow-up questions.
