### ISSUE TITLE
--train.epochs paramater not working

### ISSUE THREAD

**Issue by antoinekrajnc** [Lightning-AI/litgpt#1820]
### Bug description

Hi there 👋

First thanks for this awesome library you guys built! 

I just have what I believe is a bug when using the `litgpt pretrain` command when you want to set a fixed number of **epochs**

I want to run a pretraining job on a custom dataset using the following command:

```bash 
litgpt pretrain Phi-3.5-mini-instruct \
   --initial_checkpoint_dir checkpoints/microsoft/Phi-3.5-mini-instruct \
   --tokenizer_dir checkpoints/microsoft/Phi-3.5-mini-instruct \
   --out_dir ./new_pretrained_checkpoint \
   --data TextFiles \
   --data.train_data_path Text_files \
   --train.max_tokens 1_000_000 \
   --train.max_seq_length 1000 \
   --train.epochs 25
```

Here is the error we get: 

```
ValueError: /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/pretrain.py doesn't support the 'epochs' argument. This is set in TrainArgs(save_interval=1000, log_interval=1, global_batch_size=512, micro_batch_size=4, lr_warmup_steps=2000, lr_warmup_fraction=None, epochs=25, max_tokens=1000000, max_steps=None, max_seq_length=1000, tie_embeddings=False, max_norm=1.0, min_lr=4e-05)
```

I'm currently using `Version: 0.5.3`

### What operating system are you using?

Linux

### LitGPT Version

```
Version: 0.5.3
```

**Comment by antoinekrajnc** [comment]
Apologies, I see that it hasn't been tackled yet and in the "TO DO"

**Comment by rasbt** [comment]
Thanks for reporting, and yes, the support for fixing the number of epochs is not supported yet but will hopefully be added in the future.
