### ISSUE TITLE
All models fail to run queries on lambdalabs with error: TypeError: LLM.generate() got an unexpected keyword argument 'max_new_token'`

### ISSUE THREAD

**Issue by StainlessStlRat** [Lightning-AI/litgpt#1872]
### Bug description

I'm just running some simple inference experiments using this great library, but can't seem to get any models to run. I can load them fine, but any queries produce the following error, no matter which model I try.

Some decorator seems to be passing off an unsupported argument. How can I fix this?

`[~/models/litgpt_wrap.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/models/litgpt_wrap.py) in run_query(self, query)
      8 
      9     def run_query(self, query: str) -> str:
---> 10         return self.llm.generate(LitGPTModel._format_query(query), top_k=1) #, max_new_tokens=50)
     11 
     12     @staticmethod

[/usr/lib/python3/dist-packages/torch/utils/_contextlib.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/usr/lib/python3/dist-packages/torch/utils/_contextlib.py) in decorate_context(*args, **kwargs)
    114     def decorate_context(*args, **kwargs):
    115         with ctx_factory():
--> 116             return func(*args, **kwargs)
    117 
    118     return decorate_context

TypeError: LLM.generate() got an unexpected keyword argument 'max_new_token'`

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.5.3
```

**Comment by Andrei-Aksionov** [comment]
Hello @StainlessStlRat 

The argument should be `max_new_tokens` (plural) 🙂 
https://github.com/Lightning-AI/litgpt/blob/main/litgpt/api.py#L450

**Comment by StainlessStlRat** [comment]
Hi @Andrei-Aksionov thanks. But if you re-check that parameter is actually commented out. I am not passing "max_new_token" or "max_new_tokens" down. It automatically being added by some decorator apparently

**Comment by Andrei-Aksionov** [comment]
yeah, didn't notice that it was commented out.

But, if you search the code in the repo, you will notice that nothing provides `max_new_token`, only `max_new_tokens`.

So that something else.

----

You can try to delete this variable before calling .generate

```python
if "max_new_token" in locals():
    del max_new_token
```

You can go further and try to detect when this variable is assigned

```python
class DetectMaxNewTokenAssignment(dict):
    def __setitem__(self, key, value):
        if key == "max_new_token":
            # print some debug info to help locate when it's happening
        super().__setitem__(key, value)

globals = DetectMaxNewTokenAssignment(globals())
```

or, if you have an access to the source code, just search for `max_new_token` 🙂

**Comment by StainlessStlRat** [comment]
I will try this! But I am very confused by what the "something else" could be. I've tried searching around to see how it's happening, but I don't see anything. 

It is a completely clean lamdalabs environment with the only package installed on top being litgpt

**Comment by StainlessStlRat** [comment]
It almost seems like whatever is preparing the query arguments is deleting the last character from max_new_tokens. Although I have no idea where this is happening as it doesn't appear to be in the LitGPT/api.py file

**Comment by Andrei-Aksionov** [comment]
Then I am confused 🙂 

```python
`[~/models/litgpt_wrap.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/models/litgpt_wrap.py) in run_query(self, query)
8
9 def run_query(self, query: str) -> str:
---> 10 return self.llm.generate(LitGPTModel._format_query(query), top_k=1) #, max_new_tokens=50)
```

`models/litgpt_wrap.py` is not a part of the repo.

So, I assume, there is something else that uses LitGPT inside it. And the code, that wraps around LItGPT, might provide `max_new_token`.

----

Try to modify it this way:

```python
def run_query(self, query: str) -> str:
    if "max_new_token" in locals():
        del max_new_token
    return self.llm.generate(LitGPTModel._format_query(query), top_k=1) #, max_new_tokens=50)
```

**Comment by StainlessStlRat** [comment]
That's just my very thin wrapper around litgpt

`from litgpt import LLM
from config import Config

class LitGPTModel():

    def __init__(self, config: Config):
        self.llm = LLM.load(config.model_name)

    def run_query(self, query: str) -> str:
        return self.llm.generate(LitGPTModel._format_query(query), top_k=1) #, max_new_tokens=50)
    
    @staticmethod
    def _format_query(query):
        return f'{query}'`
        
        but I'll check!

**Comment by StainlessStlRat** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/tmp/ipykernel_3501/478649054.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/tmp/ipykernel_3501/478649054.py) in <module>
      1 query = "What are stars made of?"
----> 2 model.run_query(query)

[~/models/litgpt_wrap.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/models/litgpt_wrap.py) in run_query(self, query)
      8 
      9     def run_query(self, query: str) -> str:
---> 10         if "max_new_token" in locals():
     11             print("max new token was in there")
     12             del max_new_token

[/usr/lib/python3/dist-packages/torch/utils/_contextlib.py](https://a4dc813efbec4800bbfbd8d6cafc0026-0.lambdaspaces.com/usr/lib/python3/dist-packages/torch/utils/_contextlib.py) in decorate_context(*args, **kwargs)
    114     def decorate_context(*args, **kwargs):
    115         with ctx_factory():
--> 116             return func(*args, **kwargs)
    117 
    118     return decorate_context

TypeError: LLM.generate() got an unexpected keyword argument 'max_new_token'
```
:(

**Comment by Andrei-Aksionov** [comment]
It looks like we didn't make a release for a while.
Perhaps try to install litgpt from the main branch.

**Comment by StainlessStlRat** [comment]
Ok @Andrei-Aksionov you mean to build it/use it from source instead of pip-ing it?

**Comment by Andrei-Aksionov** [comment]
Based on the version that you provided in the very first comment (0.5.3) you most likely installed it via
```bash
pip install litgpt
```

The very latest one is `0.5.4.dev1`. 

You can install with pip directly from the github:
```bash
pip install git+https://github.com/Lightning-AI/litgpt.git
```

or git clone the repo and install it as described in the Readme:
```bash
pip install 'litgpt[all]'
```

**Comment by StainlessStlRat** [comment]
Thank you so much, I will try this and report back!

**Comment by StainlessStlRat** [comment]
For some reason the git method didn't work :( I will try from source

```
pip install git+https://github.com/Lightning-AI/litgpt.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Lightning-AI/litgpt.git
  Cloning https://github.com/Lightning-AI/litgpt.git to /tmp/pip-req-build-0mu2kt1b
  Running command git clone --filter=blob:none --quiet https://github.com/Lightning-AI/litgpt.git /tmp/pip-req-build-0mu2kt1b
  Resolved https://github.com/Lightning-AI/litgpt.git to commit a0f5bd32eee0c464fbe2abc3650fe07b77d76653
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ubuntu@192-222-54-188:~/rag$ pip show litgpt
WARNING: Package(s) not found: litgpt
```

**Comment by StainlessStlRat** [comment]
Building from source worked

**Comment by Andrei-Aksionov** [comment]
Hello @StainlessStlRat 

Thanks for the confirmation.

> So that something else.

Now we know what was that something else 😄 

I'll make a release later this week, so there is no need to install from source.
And sorry for the inconvenience.
