### ISSUE TITLE
Support chat-like data formats (e.g. ShareGPT / Vicuna)

### ISSUE THREAD

**Issue by ehartford** [Lightning-AI/litgpt#308]
Please add support for ShareGPT / Vicuna format

**Comment by JustinGoheen** [comment]
Hi @ehartford! Thanks for raising this question. We have support for ShareGPT / Vicuna, please check out our [Vicuna Tutorial](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_vicuna.md).

**Comment by ehartford** [comment]
nah... I'm not talking about loading the vicuna model.

I am talking about fine-tuning any model, with input file in ShareGPT format (as opposed to Alpaca format)

ShareGPT format is like this:

```
{
    "id": "oijerhowe4",
    "conversations": [
      {
        "from": "user",
        "value": "what time is it?"
      },
      {
        "from": "gpt",
        "value": "I do not have any way to retrieve that information for you."
      },
      {
        "from": "user",
        "value": "ok then what day of the week is it?"
      },
      {
        "from": "gpt",
        "value": "I can't answer that question either.  I don't have a clock or a calendar, so I can't tell you the day or the time."
      },
    ]
}
```

**Comment by thisislsj** [comment]
It would be great have a built-in method to finetune llama2-chat models for multi turn conversations like this in contrast to alpaca format.

**Comment by JustinGoheen** [comment]
cc @carmocca @awaelchli

**Comment by drevit-doc** [comment]
are there any updates about this? It would be a great feature

**Comment by Nanayeb34** [comment]
@carmocca has this been resolved? can't seem to see any proposed solution. i want to prepare my dataset in the sharegpt format as well as opposed to alpaca

**Comment by rasbt** [comment]
Hi there. Unfortunately, we haven't added multi-turn question support, but I agree that it's something we should look into and tackle.
