### ISSUE TITLE
Enable Logging for Weights and Biases

### ISSUE THREAD

**Issue by ayulockin** [Lightning-AI/litgpt#440]
I think it is easy to configure the finetuning scripts (this is the main focus for now given the NeurIPS challenge) with support for experiment tracking tools like Weights and Biases.

I have created a gist [here](https://gist.github.com/ayulockin/d95cc595158f3d2b3a3e290b524f4421) with the relevant changes to the `finetune/lora.py` file (find "W&B" mention).

If this is of interest, I would love to open a PR.

**Comment by JustinGoheen** [comment]
@ayulockin How about collaborating on an integration for Fabric? I opened a feature request:

➡️  https://github.com/Lightning-AI/lightning/issues/18397

**Comment by JustinGoheen** [comment]
...actually, a feature request already exists:

https://github.com/Lightning-AI/lightning/issues/17885

I closed the issue I opened earlier.

**Comment by rasbt** [comment]
Thanks to @awaelchli  there's now a `--logger_name` option where you can choose `--logger_name "wandb"` for example. Let us know if there are any follow-up questions or issues.
