### ISSUE TITLE
lit-gpt as a script and as a package?

### ISSUE THREAD

**Issue by Anindyadeep** [Lightning-AI/litgpt#548]
I have come across and played around with this awesome repo for quite a while. I wonder, can we convert this repository as a modular package? What I mean by modular here is, not a completely black box library. When It comes to fine-tuning or pre-training or deploying LLMs, there is a tradeoff between levels of customizability and the pain of doing things from scratch. 

Suppose, I want to make very specific changes to model architecture (keeping everything the same) or want to make some changes in the fine-tuning process (like instead of PPO, I want to implement DPO or maybe a new algorithm), so I only need to implement that keeping other things simple, but in a modular way. Currently, lit-gpt is awesome to take the script and modify it in our own way. However, I feel like the usage of this repository as a script and as a package might be useful (or maybe keeping lit-gpt the same and having a `lit-llm` like package inheriting from lit-gpt?). Because I am aware of lightning's deployment infra. So I was thinking can it be linked directly to the creation of these models?

Please do let me know where the priorities are aligned. Would love to discuss more on this. 
Thanks

**Comment by carmocca** [comment]
What would be the benefit of having a package for you precisely? Is it calling the scripts without cloning the repository? I'd like to understand exactly what you would want to import.

The `lit-gpt` directory is `pip` installable.

**Comment by rasbt** [comment]
I think this would be more of a long-term thing, but I can see how a modular package could be useful one day once the LLM ecosystem is more mature (right now, there are so many changes that it would make it hard to develop a modular package, and it's easier to have these hackable scripts). With modular package, I assume OP means something like scikit-learn
