### ISSUE TITLE
randomised training data

### ISSUE THREAD

**Issue by mayyankgarg** [Lightning-AI/litgpt#590]
Hi,

I went through finetune/lora.py and saw that random batch is being fetched and used in training. Would it better if I use a dataloader which tracks samples already used in training? Plus, doesn't validation and saving checkpoint on nth tokens trained be better choice? Can we have more control on this - save by tokens trained, iteration steps?

**Comment by rasbt** [comment]
I agree that using a DataLoader for the finetuning scripts would be a good idea.
