### ISSUE TITLE
Problem with finetune_adapter.py along with fix

### ISSUE THREAD

**Issue by RDouglasSharp** [Lightning-AI/litgpt#61]
AttributeError: 'Parrot' object has no attribute 'rope_cache'
lit-parrot/lit_parrot/model.py:67 in forward 
❱  67 │   │   if self.rope_cache is None:                                                        │
│    68 │   │   │   self.rope_cache = self.build_rope_cache(idx)

Problem is due to lit_parrot/adapter.py initialization initializing the super super class instead of the super class:

     Should be - 
class CausalSelfAttention(BaseModel):
    """A modification of `lit_parrot.model.CausalSelfAttention` that adds the attention
    over the adaption prompt."""

    def __init__(self, config: Config, block_idx: int) -> None:
        super().__init__(config)

Instead of:
class CausalSelfAttention(nn.Module):
    """A modification of `lit_parrot.model.CausalSelfAttention` that adds the attention
    over the adaption prompt."""

    def __init__(self, config: Config, block_idx: int) -> None:
        super().__init__()

**Comment by RDouglasSharp** [comment]
Issue is still there, but my fix is not correct

**Comment by ArturK-85** [comment]
@RDouglasSharp after making changes i'm worried that the model without kv cache was fit for training in 12GB Vram and now it gets OOM, it seems to me that kv cache should only be used for inference or am I wrong?

**Comment by ArturK-85** [comment]
@RDouglasSharp 
With implemented yours solution from #58
i proposed change initialization in adapter.py not in CassualSelfAttention, but in Parrot to

'super()__init__(config)' ,

I don't know why the memory usage is increasing, this is a big problem compared to the previous implementation allowing you to train on hardware with less memory.  You may need to implement some logic to disable kv_cache for fine tuning

**Comment by bkiat1123** [comment]
Memory is back to below 12GB.
 
The reason we cannot call `super().__init__(config)` in Adapter class is because the parent class will load the weights during initialization too. This require twice the memory. Therefore, we skip the parent class and call `nn.Module__init__(self)` directly.

**Comment by RDouglasSharp** [comment]
Yes - realized that... that is why I commented "Issue is still there, but my fix is not correct" ...  thanks so much for fixing this...  my fine tuning is now running ... just barely ... fine tuning stabilityai/stablelm-tuned-alpha-7b on 3090 with fumes left in terms of GPU memory.

**Comment by ArturK-85** [comment]
Yes it works verry well, inference with kv_cache and fine tuning without it for vram memory save
