### ISSUE TITLE
Prefix Sufix finetune  and inference

### ISSUE THREAD

**Issue by DavidGOrtega** [Lightning-AI/litgpt#826]
The framework should move to the more flexible (and already known) prefix sufix architecture to allow datasets with prompts different to Alpaca.

`scripts/prepare_any.py` and ideal `generate.py` would accept `tokenizer`, `prefix`, `suffix` and `bos` and `eos` tokens. 

related to #825

**Comment by carmocca** [comment]
Hi!

This is not the answer that you'd like to hear, but this project is not meant to be a framework but a collection of hackable scripts around a powerful model implementation.

We make everything more configurable and add arguments everywhere, but that would take away from the simplicity of the code.

The tradeoff is that users (you) need to make changes to the code and adapt it to their desired data format, etc.

**Comment by Qubitium** [comment]
@carmocca  Resonable but I also agree with @DavidGOrtega. Lora is not alpaca. 

Perhaps if lit-gpt is just collection of scripts, rename it to lora_alpaca?

**Comment by carmocca** [comment]
The current `finetune/lora.py` implementation uses "alpaca" as path names: https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/lora.py#L61-L63 but you could use any of the other prepare_scripts that use the instruction format, for instance lima: https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/prepare_lima.py, https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/prepare_dataset.md#preparing-datasets

**Comment by DavidGOrtega** [comment]
Indeed I have two models trained with lit-gpt one is unstructured data and the other is a whole analysis of a transcription.
As I stated in #825 the only dependency is the path that could be whatever, then remove the Alpaca prompter and that would be enough to have a lora generator. The only difference is that the lora adds the lora weights to the model.
Merge the weights is not ideal for me and probably for many.
