### ISSUE TITLE
add DeciAI LLM

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/litgpt#827]
[DeciLM-7B](https://huggingface.co/Deci/DeciLM-7B) seem to be the best 7B LLM at the moment and worth adding it.

**Comment by 02shanks** [comment]
@aniketmaurya is this issue still open for contribution?

**Comment by rasbt** [comment]
Hi there and thanks for the interest. But I would say that adding this model is no longer necessary as it is almost 1 year old, and there have been many better models in the meantime. Thanks for your interest in contributing though! Please feel free to consider one of the other items listed in the issue list in case you are interested.
