### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by parnashri** [Lightning-AI/litgpt#845]
Cannot generate the model and the error message displays CUDA out of memory and asking to use torch.utils._pytree.register_pytree_node. Tried by killing ongoing processes but not working. Help me out

**Comment by carmocca** [comment]
Can you share the complete error stacktrace?

**Comment by parnashri** [comment]
[image: image.png]
This is the error I've been receiving. The computer that I'm using is new
one still it shows no memory.

**Comment by carmocca** [comment]
It doesn't seem like you linked the image properly
