### ISSUE TITLE
Question about unstructured datasets

### ISSUE THREAD

**Issue by PottedRosePetal** [Lightning-AI/litgpt#858]
In the lit-llama repo there is a file about unstructured datasets (https://github.com/Lightning-AI/lit-llama/blob/main/howto/unstructured_dataset.md#finetuning-on-an-unstructured-dataset). Is this also applicable to lit-gpt? and if so, does it work with LoRA? (the linked file is ambiguous there... shouldnt be "either" but rather "both" or "neither".)

**Comment by Andrei-Aksionov** [comment]
Hello @PottedRosePetal 

I haven't tried it personally, but I don't see any reason why it shouldn't work.
It's all about training to predict the next token. 
Structured here means that there is a special structure to tell the model where instruction and response starts/ends. It's usually either a special token, new line characters, or both. [Here](https://github.com/Lightning-AI/lit-gpt/blob/cd1c521d8dddbb07f7fc8b6a45b2a4f74b6892ea/chat/base.py#L200) you can see examples of such structures.
In the end, it's just a string that is fed into a model (well, into a tokenizer first :)).

The same goes to LoRA - it should work without any problems. LoRA is just a way to [efficiently update](https://github.com/Lightning-AI/lit-gpt/blob/cd1c521d8dddbb07f7fc8b6a45b2a4f74b6892ea/lit_gpt/lora.py#L7-L42) pretrained weights.

My only recommendation is to use a base model, not an instruction variant. A base model typically is trained on an unstructured text, so in this case you will simply continue pretraining.

**Comment by Andrei-Aksionov** [comment]
It might work.
At least I don't see any technical obstacles.
