### ISSUE TITLE
Hang on two gpu training

### ISSUE THREAD

**Issue by TeddLi** [Lightning-AI/litgpt#901]
Hi there, I try to run pretrain tiny-llama with 8GPU server. 
If I only use one GPU is fine. After I changed to multiGPU it just hung, The NCCL log of two-gpu run
 is listed below.
```
The error msg is Estimated TFLOPs: 84.51
g3-xlarge-x86-dal-1:3263:3263 [0] NCCL INFO Bootstrap : Using eno1:160.202.129.119<0>
g3-xlarge-x86-dal-1:3263:3263 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
g3-xlarge-x86-dal-1:3263:3263 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
g3-xlarge-x86-dal-1:3263:3263 [0] NCCL INFO cudaDriverVersion 12010
NCCL version 2.18.1+cuda12.1
g3-xlarge-x86-dal-1:3419:3419 [1] NCCL INFO cudaDriverVersion 12010
g3-xlarge-x86-dal-1:3419:3419 [1] NCCL INFO Bootstrap : Using eno1:160.202.129.119<0>
g3-xlarge-x86-dal-1:3419:3419 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
g3-xlarge-x86-dal-1:3419:3419 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
g3-xlarge-x86-dal-1:3419:3812 [1] NCCL INFO Failed to open libibverbs.so[.1]
g3-xlarge-x86-dal-1:3419:3812 [1] NCCL INFO NET/Socket : Using [0]eno1:160.202.129.119<0> [1]eno2:10.87.1.117<0>
g3-xlarge-x86-dal-1:3419:3812 [1] NCCL INFO Using network Socket
g3-xlarge-x86-dal-1:3263:3811 [0] NCCL INFO Failed to open libibverbs.so[.1]
g3-xlarge-x86-dal-1:3263:3811 [0] NCCL INFO NET/Socket : Using [0]eno1:160.202.129.119<0> [1]eno2:10.87.1.117<0>
g3-xlarge-x86-dal-1:3263:3811 [0] NCCL INFO Using network Socket
```
4 GPU and 8 GPU training is even worse, the code will stuck there and I have to restart to get my control

![image](https://github.com/Lightning-AI/lit-gpt/assets/67747139/01e1eb1d-3f0f-49d2-810c-9d2cdd66cbfa)

My cuda version is 12.1

**Comment by awaelchli** [comment]
@TeddLi I would take a raw PyTorch example to test multi-GPU (https://github.com/pytorch/examples/tree/main/distributed)? To me it looks like any PyTorch multi-GPU would have trouble on your machine. It's unlikely specific to Lightning or lit-gpt. And why are you setting `export NCCL_P2P_DISABLE=1`, this should not be disabled otherwise you will get a horribly slow GPU connection.

**Comment by awaelchli** [comment]
@TeddLi So it looks like PyTorch/NCCL is not able to set up the communication between the GPUs. It's not related to Lightning. I can only guess, these things are hard to diagnose. 

Often on some systems, it is because of IOMMU. Try to disable it:
https://github.com/pytorch/pytorch/issues/24081#issuecomment-557074611
https://github.com/pytorch/pytorch/issues/24081#issuecomment-569437435
But I don't know if that will help. I only know it's not uncommon, so maybe worth a try. Also make sure your GPU driver is up-to date for your system.

**Comment by awaelchli** [comment]
I don't have anymore ideas. I suggest you also ask on the PyTorch forum.

**Comment by VJJJJJJ1** [comment]
> Hey [@awaelchli](https://github.com/awaelchli) Sry to interrupt, I hit the hang again during evaluate with multi-gpu FSDP setting. The error is listed below
> 
> ```
> terminate called after throwing an instance of 'c10::DistBackendError'
>   what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=77387, OpType=_ALLGATHER_BASE, NumelIn=54528000, NumelOut=218112000, Timeout(ms)=20000000) ran for 20000896 milliseconds before timing out.
> Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
> frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f720b581d87 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
> frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7f71c0fdf6e6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
> frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7f71c0fe2c3d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
> frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7f71c0fe3839 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
> frame #4: <unknown function> + 0xdc253 (0x7f720acb0253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
> frame #5: <unknown function> + 0x94ac3 (0x7f720ccdcac3 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #6: clone + 0x44 (0x7f720cd6da04 in /lib/x86_64-linux-gnu/libc.so.6)
> 
> Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1186 (most recent call first):
> frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f720b581d87 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
> frame #1: <unknown function> + 0xdf6b11 (0x7f71c0d39b11 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
> frame #2: <unknown function> + 0xdc253 (0x7f720acb0253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
> frame #3: <unknown function> + 0x94ac3 (0x7f720ccdcac3 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #4: clone + 0x44 (0x7f720cd6da04 in /lib/x86_64-linux-gnu/libc.so.6)
> ```

same problem, have you solved it?
