### ISSUE TITLE
Remove `config_path` from `convert_lit_checkpoint.py`

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/litgpt#981]
I guess we could get rid of the `config_path` argument now

_Originally posted by @carmocca in https://github.com/Lightning-AI/lit-gpt/pull/965#discussion_r1508225119_

**Comment by rasbt** [comment]
Before doing that, we would still need to copy the `config.json` file to the model-containing directory generated by the finetuning scripts. I suggest we get rid of the `config_path` in the same PR that copies those files. I can work on that.

**Comment by rasbt** [comment]
Tagging the related PR I mentioned above #984

**Comment by awaelchli** [comment]
@rasbt Would you like to take this one? Now that there is a guarantee that every lit-gpt checkpoint contains the lit_config.json, we can automatically load it from the input checkpoint dir:

```py
config = Config.from_json(checkpoint_path / "lit_config.json")
```

Would be a nice quality of life improvement, one less argument to remember 😃

**Comment by rasbt** [comment]
Yes, I can happily do that!
